package ashara

type PermissionFlags BitSet

const (
	CREATE_INSTANT_INVITE_PERMISSION PermissionFlags = 1 << iota
	KICK_MEMBERS_PERMISSION
	BAN_MEMBERS_PERMISSION
	ADMINISTRATOR_PERMISSION
	MANAGE_CHANNELS_PERMISSION
	MANAGE_GUILD_PERMISSION
	ADD_REACTIONS_PERMISSION
	VIEW_AUDIT_LOG_PERMISSION
	PRIORITY_SPEAKER_PERMISSION
	STREAM_PERMISSION
	VIEW_CHANNEL_PERMISSION
	SEND_MESSAGES_PERMISSION
	SEND_TTS_MESSAGES_PERMISSION
	MANAGE_MESSAGES_PERMISSION
	EMBED_LINKS_PERMISSION
	ATTACH_FILES_PERMISSION
	READ_MESSAGE_HISTORY_PERMISSION
	MENTION_EVERYONE_PERMISSION
	USE_EXTERNAL_EMOJIS_PERMISSION
	VIEW_GUILD_INSIGHTS_PERMISSION
	CONNECT_PERMISSION
	SPEAK_PERMISSION
	MUTE_MEMBERS_PERMISSION
	DEAFEN_MEMBERS_PERMISSION
	MOVE_MEMBERS_PERMISSION
	USE_VAD_PERMISSION
	CHANGE_NICKNAME_PERMISSION
	MANAGE_NICKNAMES_PERMISSION
	MANAGE_ROLES_PERMISSION
	MANAGE_WEBHOOKS_PERMISSION
	MANAGE_GUILD_EXPRESSIONS_PERMISSION
	USE_APPLICATION_COMMANDS_PERMISSION
	REQUEST_TO_SPEAK_PERMISSION
	MANAGE_EVENTS_PERMISSION
	MANAGE_THREADS_PERMISSION
	CREATE_PUBLIC_THREADS_PERMISSION
	CREATE_PRIVATE_THREADS_PERMISSION
	USE_EXTERNAL_STICKERS_PERMISSION
	SEND_MESSAGES_IN_THREADS_PERMISSION
	USE_EMBEDDED_ACTIVITIES_PERMISSION
	MODERATE_MEMBERS_PERMISSION
	VIEW_CREATOR_MONETIZATION_ANALYTICS_PERMISSION
	USE_SOUNDBOARD_PERMISSION
	CREATE_GUILD_EXPRESSIONS_PERMISSION
	CREATE_EVENTS_PERMISSION
	USE_EXTERNAL_SOUNDS_PERMISSION
	SEND_VOICE_MESSAGES_PERMISSION
	_
	_
	SEND_POLLS_PERMISSION
	USE_EXTERNAL_APPS_PERMISSION

	ALL_TEXT_PERMISSIONS = VIEW_CHANNEL_PERMISSION |
		SEND_MESSAGES_PERMISSION |
		SEND_TTS_MESSAGES_PERMISSION |
		MANAGE_MESSAGES_PERMISSION |
		EMBED_LINKS_PERMISSION |
		ATTACH_FILES_PERMISSION |
		READ_MESSAGE_HISTORY_PERMISSION |
		MENTION_EVERYONE_PERMISSION |
		SEND_VOICE_MESSAGES_PERMISSION |
		SEND_POLLS_PERMISSION |
		USE_EXTERNAL_APPS_PERMISSION

	ALL_THREAD_PERMISSIONS = MANAGE_THREADS_PERMISSION |
		CREATE_PUBLIC_THREADS_PERMISSION |
		CREATE_PRIVATE_THREADS_PERMISSION |
		SEND_MESSAGES_IN_THREADS_PERMISSION

	ALL_VOICE_PERMISSIONS = VIEW_CHANNEL_PERMISSION |
		CONNECT_PERMISSION |
		SPEAK_PERMISSION |
		STREAM_PERMISSION |
		MUTE_MEMBERS_PERMISSION |
		DEAFEN_MEMBERS_PERMISSION |
		MOVE_MEMBERS_PERMISSION |
		USE_VAD_PERMISSION |
		PRIORITY_SPEAKER_PERMISSION |
		USE_SOUNDBOARD_PERMISSION |
		USE_EXTERNAL_SOUNDS_PERMISSION |
		REQUEST_TO_SPEAK_PERMISSION |
		USE_EMBEDDED_ACTIVITIES_PERMISSION |
		CREATE_GUILD_EXPRESSIONS_PERMISSION |
		CREATE_EVENTS_PERMISSION |
		MANAGE_EVENTS_PERMISSION

	ALL_CHANNEL_PERMISSIONS = ALL_TEXT_PERMISSIONS |
		ALL_THREAD_PERMISSIONS |
		ALL_VOICE_PERMISSIONS |
		CREATE_INSTANT_INVITE_PERMISSION |
		MANAGE_CHANNELS_PERMISSION |
		ADD_REACTIONS_PERMISSION |
		USE_EXTERNAL_EMOJIS_PERMISSION |
		USE_APPLICATION_COMMANDS_PERMISSION |
		USE_EXTERNAL_STICKERS_PERMISSION

	ALL_PERMISSIONS = ALL_CHANNEL_PERMISSIONS |
		KICK_MEMBERS_PERMISSION |
		BAN_MEMBERS_PERMISSION |
		MANAGE_GUILD_PERMISSION |
		ADMINISTRATOR_PERMISSION |
		MANAGE_WEBHOOKS_PERMISSION |
		MANAGE_GUILD_EXPRESSIONS_PERMISSION |
		VIEW_CREATOR_MONETIZATION_ANALYTICS_PERMISSION |
		VIEW_GUILD_INSIGHTS_PERMISSION |
		VIEW_AUDIT_LOG_PERMISSION |
		MANAGE_ROLES_PERMISSION |
		CHANGE_NICKNAME_PERMISSION |
		MANAGE_NICKNAMES_PERMISSION |
		MODERATE_MEMBERS_PERMISSION
)
