# Workflow to perform code quality checks on each commit/PR to main
name: Code Quality
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - "main"
  push:
    branches:
      - "main"
  merge_group:
    types: [checks_requested]
  # allow manually triggering on branches
  workflow_dispatch:

permissions:
  contents: read

env:
  go_version: '1.23.x'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lefthook:
    name: Lint with Lefthook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
          check-latest: true
          cache: true

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

      - name: Install Lefthook
        run: go install github.com/evilmartians/lefthook/v2@latest

      - name: Run Lefthook
        run: lefthook run pre-commit
