# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.26.4'

    - name: Build
      run: go build -v ./...

    - name: Install fieldalignment
      run: go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest

    - name: Check field alignment
      run: fieldalignment ./...

    - name: Test
      run: go test -v ./...

